/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WeatherSnapshot = IDL.Record({
  'precipitation' : IDL.Float64,
  'temperature' : IDL.Float64,
  'weatherDescription' : IDL.Text,
  'humidity' : IDL.Float64,
});
export const AddPredictionRecordRequest = IDL.Record({
  'farmerSessionId' : IDL.Nat,
  'weatherSnapshot' : WeatherSnapshot,
  'confidenceScore' : IDL.Float64,
  'diseaseName' : IDL.Text,
  'cropType' : IDL.Text,
});
export const Time = IDL.Int;
export const PredictionRecord = IDL.Record({
  'id' : IDL.Nat,
  'farmerSessionId' : IDL.Nat,
  'weatherSnapshot' : WeatherSnapshot,
  'confidenceScore' : IDL.Float64,
  'diseaseName' : IDL.Text,
  'timestamp' : Time,
  'cropType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPredictionRecord' : IDL.Func([AddPredictionRecordRequest], [IDL.Nat], []),
  'getPredictionRecordById' : IDL.Func(
      [IDL.Nat],
      [PredictionRecord],
      ['query'],
    ),
  'getRecordsBySessionId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PredictionRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WeatherSnapshot = IDL.Record({
    'precipitation' : IDL.Float64,
    'temperature' : IDL.Float64,
    'weatherDescription' : IDL.Text,
    'humidity' : IDL.Float64,
  });
  const AddPredictionRecordRequest = IDL.Record({
    'farmerSessionId' : IDL.Nat,
    'weatherSnapshot' : WeatherSnapshot,
    'confidenceScore' : IDL.Float64,
    'diseaseName' : IDL.Text,
    'cropType' : IDL.Text,
  });
  const Time = IDL.Int;
  const PredictionRecord = IDL.Record({
    'id' : IDL.Nat,
    'farmerSessionId' : IDL.Nat,
    'weatherSnapshot' : WeatherSnapshot,
    'confidenceScore' : IDL.Float64,
    'diseaseName' : IDL.Text,
    'timestamp' : Time,
    'cropType' : IDL.Text,
  });
  
  return IDL.Service({
    'addPredictionRecord' : IDL.Func(
        [AddPredictionRecordRequest],
        [IDL.Nat],
        [],
      ),
    'getPredictionRecordById' : IDL.Func(
        [IDL.Nat],
        [PredictionRecord],
        ['query'],
      ),
    'getRecordsBySessionId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };